from iceyard_api.operations.schemas import OperationDescriptor

E_SQL = ["spark", "trino", "flink", "embedded"]
E_SPARK = ["spark", "embedded"]
E_MAINTENANCE = ["spark", "trino", "embedded"]
E_TRINO = ["trino"]
E_DUCKDB = ["embedded"]

CATEGORY_ORDER = [
    "Namespace",
    "Table DDL",
    "Schema",
    "Partition",
    "DML",
    "Time travel",
    "Metadata tables",
    "Branch and tag",
    "Snapshots",
    "Maintenance",
    "Tuning",
    "Retention",
    "Stats and CDC",
    "Migration",
    "Views",
    "Engine specific",
]


def param(
    name: str,
    type_: str = "string",
    *,
    required: bool = False,
    default: object | None = None,
    options: list[str] | None = None,
    placeholder: str | None = None,
    advanced: bool = False,
    show_if: dict[str, object] | None = None,
) -> dict[str, object]:
    return {
        "name": name,
        "type": type_,
        "required": required,
        "default": default,
        "options": options,
        "placeholder": placeholder,
        "advanced": advanced,
        "show_if": show_if,
    }


def default_gates(
    safety_class: str,
    gates: list[str] | None,
) -> list[str]:
    if gates is not None:
        return gates
    if safety_class == "READ":
        return []
    if safety_class == "METADATA":
        return ["dry_run_required"]
    if safety_class == "WRITE":
        return ["dry_run_required", "affected_row_estimate"]
    if safety_class == "REWRITE":
        return ["dry_run_required", "restore_point_required", "idempotent_retry"]
    if safety_class == "DESTRUCTIVE":
        return ["dry_run_required", "restore_point_required", "approval_required"]
    return ["dry_run_required", "same_location_collision_check", "idempotent_retry"]


def op(
    id_: str,
    name: str,
    category: str,
    safety_class: str,
    supported_engines: list[str],
    sql_template: str,
    *,
    description: str,
    params: list[dict[str, object]] | None = None,
    dry_run_supported: bool = True,
    approval_required: bool | None = None,
    restore_point_required: bool | None = None,
    gates: list[str] | None = None,
) -> dict[str, object]:
    destructive = safety_class == "DESTRUCTIVE"
    rewrite = safety_class == "REWRITE"
    return {
        "id": id_,
        "name": name,
        "description": description,
        "category": category,
        "safety_class": safety_class,
        "supported_engines": supported_engines,
        "required_permissions": ["tables.read"]
        if safety_class == "READ"
        else ["operations.execute"],
        "params": params or [],
        "sql_template": sql_template,
        "dry_run_supported": dry_run_supported,
        "approval_required": destructive if approval_required is None else approval_required,
        "restore_point_required": (destructive or rewrite)
        if restore_point_required is None
        else restore_point_required,
        "gates": default_gates(safety_class, gates),
    }


RAW_OPERATIONS: list[dict[str, object]] = [
    op(
        "show_namespaces",
        "Show namespaces",
        "Namespace",
        "READ",
        E_SQL,
        "SHOW NAMESPACES IN {catalog}",
        description="List namespaces visible in a catalog.",
        params=[param("catalog", default="iceyard")],
    ),
    op(
        "create_namespace",
        "Create namespace",
        "Namespace",
        "METADATA",
        E_SQL,
        "CREATE NAMESPACE {catalog}.{namespace}",
        description="Create an Iceberg namespace.",
        params=[param("namespace", required=True, placeholder="analytics")],
    ),
    op(
        "create_namespace_props",
        "Create namespace with properties",
        "Namespace",
        "METADATA",
        ["spark", "trino"],
        "CREATE NAMESPACE {catalog}.{namespace} WITH PROPERTIES ({properties})",
        description="Create a namespace and set initial properties.",
        params=[
            param("namespace", required=True, placeholder="analytics"),
            param("properties", placeholder="'owner'='data-platform'"),
        ],
    ),
    op(
        "drop_namespace",
        "Drop namespace",
        "Namespace",
        "DESTRUCTIVE",
        E_SQL,
        "DROP NAMESPACE {catalog}.{namespace}",
        description="Drop an empty namespace after validation.",
        params=[param("namespace", required=True, placeholder="staging")],
        gates=["dry_run_required", "namespace_empty_check", "approval_required"],
    ),
    op(
        "alter_namespace_set_props",
        "Set namespace property",
        "Namespace",
        "METADATA",
        ["spark", "trino"],
        "ALTER NAMESPACE {catalog}.{namespace} SET PROPERTIES ('{key}' = '{value}')",
        description="Update namespace metadata properties.",
        params=[
            param("namespace", required=True, placeholder="analytics"),
            param("key", required=True, placeholder="owner"),
            param("value", required=True, placeholder="data-platform"),
        ],
    ),
    op(
        "alter_namespace_location",
        "Set namespace location",
        "Namespace",
        "METADATA",
        ["spark"],
        "ALTER NAMESPACE {catalog}.{namespace} SET LOCATION '{location}'",
        description="Move the default namespace warehouse location.",
        params=[
            param("namespace", required=True, placeholder="analytics"),
            param("location", required=True, placeholder="s3://lakehouse/analytics"),
        ],
        gates=["dry_run_required", "path_authority_check"],
    ),
    op(
        "describe_namespace",
        "Describe namespace",
        "Namespace",
        "READ",
        ["spark", "trino"],
        "DESCRIBE NAMESPACE EXTENDED {catalog}.{namespace}",
        description="Inspect namespace properties and location.",
        params=[param("namespace", required=True, placeholder="analytics")],
    ),
    op(
        "show_tables",
        "Show tables",
        "Namespace",
        "READ",
        E_SQL,
        "SHOW TABLES IN {catalog}.{namespace}",
        description="List tables in a namespace.",
        params=[param("namespace", required=True, placeholder="analytics")],
    ),
    op(
        "create_table",
        "Create table",
        "Table DDL",
        "METADATA",
        E_SQL,
        "CREATE TABLE {catalog}.{namespace}.{new_table} ({columns}) USING iceberg",
        description="Create an empty Iceberg table.",
        params=[
            param("namespace", default="{ns}"),
            param("new_table", required=True, placeholder="events_v2"),
            param("columns", required=True, placeholder="id bigint, ts timestamp"),
        ],
    ),
    op(
        "create_table_if_not_exists",
        "Create table if not exists",
        "Table DDL",
        "METADATA",
        E_SQL,
        "CREATE TABLE IF NOT EXISTS {catalog}.{namespace}.{new_table} ({columns}) USING iceberg",
        description="Create a table only when absent.",
        params=[
            param("namespace", default="{ns}"),
            param("new_table", required=True, placeholder="events"),
            param("columns", required=True, placeholder="id bigint, ts timestamp"),
        ],
    ),
    op(
        "create_partitioned_table",
        "Create partitioned table",
        "Table DDL",
        "METADATA",
        E_SQL,
        (
            "CREATE TABLE {catalog}.{namespace}.{new_table} ({columns}) USING iceberg "
            "PARTITIONED BY ({partitions})"
        ),
        description="Create a table with identity or transformed partitions.",
        params=[
            param("namespace", default="{ns}"),
            param("new_table", required=True, placeholder="events"),
            param("columns", required=True, placeholder="id bigint, occurred_at timestamp"),
            param("partitions", required=True, placeholder="days(occurred_at), bucket(16, id)"),
        ],
    ),
    op(
        "create_table_properties",
        "Create table with properties",
        "Table DDL",
        "METADATA",
        E_SQL,
        (
            "CREATE TABLE {catalog}.{namespace}.{new_table} ({columns}) "
            "USING iceberg TBLPROPERTIES ({properties})"
        ),
        description="Create a table with explicit table properties.",
        params=[
            param("namespace", default="{ns}"),
            param("new_table", required=True, placeholder="events"),
            param("columns", required=True, placeholder="id bigint"),
            param("properties", placeholder="'write.format.default'='parquet'"),
        ],
    ),
    op(
        "ctas",
        "Create table as select",
        "Table DDL",
        "WRITE",
        ["spark", "trino", "flink", "embedded"],
        "CREATE TABLE {catalog}.{namespace}.{new_table} USING iceberg AS\n{select_sql}",
        description="Create and populate a table from a query.",
        params=[
            param("namespace", default="{ns}"),
            param("new_table", required=True, placeholder="events_copy"),
            param("select_sql", required=True, placeholder="SELECT * FROM source.events"),
        ],
    ),
    op(
        "rtas",
        "Replace table as select",
        "Table DDL",
        "WRITE",
        ["spark", "trino"],
        "REPLACE TABLE {catalog}.{namespace}.{new_table} AS\n{select_sql}",
        description="Replace a table with query output.",
        params=[
            param("namespace", default="{ns}"),
            param("new_table", default="{table_name}"),
            param("select_sql", required=True, placeholder="SELECT * FROM source.events"),
        ],
        approval_required=True,
    ),
    op(
        "create_or_replace_table",
        "Create or replace table",
        "Table DDL",
        "METADATA",
        ["spark", "trino"],
        "CREATE OR REPLACE TABLE {catalog}.{namespace}.{new_table} ({columns}) USING iceberg",
        description="Create a table or replace its metadata definition.",
        params=[
            param("namespace", default="{ns}"),
            param("new_table", default="{table_name}"),
            param("columns", required=True, placeholder="id bigint, ts timestamp"),
        ],
        approval_required=True,
    ),
    op(
        "drop_table",
        "Drop table",
        "Table DDL",
        "DESTRUCTIVE",
        E_SQL,
        "DROP TABLE {table}",
        description="Drop a table while retaining underlying files when the engine supports it.",
        gates=["dry_run_required", "restore_point_required", "approval_required"],
    ),
    op(
        "drop_table_purge",
        "Drop table and purge data",
        "Table DDL",
        "DESTRUCTIVE",
        ["spark", "trino"],
        "DROP TABLE {table} PURGE",
        description="Drop a table and delete table data.",
        gates=[
            "dry_run_required",
            "restore_point_required",
            "purge_double_confirmation",
            "approval_required",
        ],
    ),
    op(
        "rename_table",
        "Rename table",
        "Table DDL",
        "METADATA",
        E_SQL,
        "ALTER TABLE {table} RENAME TO {catalog}.{ns}.{new_name}",
        description="Rename a table within a catalog.",
        params=[param("new_name", required=True, placeholder="events_v2")],
    ),
    op(
        "set_tblproperties",
        "Set table property",
        "Table DDL",
        "METADATA",
        E_SQL,
        "ALTER TABLE {table} SET TBLPROPERTIES ('{key}' = '{value}')",
        description="Set or replace a table property.",
        params=[
            param("key", required=True, placeholder="write.target-file-size-bytes"),
            param("value", required=True, placeholder="536870912"),
        ],
    ),
    op(
        "unset_tblproperties",
        "Unset table property",
        "Table DDL",
        "METADATA",
        ["spark", "trino"],
        "ALTER TABLE {table} UNSET TBLPROPERTIES ('{key}')",
        description="Remove a table property.",
        params=[param("key", required=True, placeholder="commit.retry.num-retries")],
    ),
    op(
        "show_create_table",
        "Show create table",
        "Table DDL",
        "READ",
        ["spark", "trino"],
        "SHOW CREATE TABLE {table}",
        description="Export the table DDL.",
    ),
    op(
        "upgrade_format",
        "Upgrade table format",
        "Table DDL",
        "DESTRUCTIVE",
        ["spark", "embedded"],
        "ALTER TABLE {table} SET TBLPROPERTIES ('format-version' = '{target_version}')",
        description="Upgrade the Iceberg table format after reader compatibility review.",
        params=[param("target_version", "integer", default="3", options=["2", "3"])],
        gates=[
            "dry_run_required",
            "reader_compatibility_check",
            "irreversible_change_check",
            "restore_point_required",
            "approval_required",
        ],
    ),
    op(
        "add_column",
        "Add column",
        "Schema",
        "METADATA",
        E_SQL,
        "ALTER TABLE {table} ADD COLUMN {column} {type}",
        description="Add a nullable or defaulted column.",
        params=[
            param("column", required=True, placeholder="device_type"),
            param("type", required=True, placeholder="string"),
        ],
        gates=["schema_compatibility"],
    ),
    op(
        "add_columns",
        "Add multiple columns",
        "Schema",
        "METADATA",
        ["spark", "trino"],
        "ALTER TABLE {table} ADD COLUMNS ({columns})",
        description="Add multiple columns in one metadata update.",
        params=[param("columns", required=True, placeholder="device_type string, country string")],
    ),
    op(
        "add_column_first",
        "Add column first",
        "Schema",
        "METADATA",
        ["spark"],
        "ALTER TABLE {table} ADD COLUMN {column} {type} FIRST",
        description="Add a column at the beginning of a schema.",
        params=[param("column", required=True), param("type", required=True, placeholder="int")],
    ),
    op(
        "add_column_after",
        "Add column after",
        "Schema",
        "METADATA",
        ["spark"],
        "ALTER TABLE {table} ADD COLUMN {column} {type} AFTER {after_column}",
        description="Add a column after another column.",
        params=[
            param("column", required=True),
            param("type", required=True, placeholder="string"),
            param("after_column", required=True, placeholder="user_id"),
        ],
    ),
    op(
        "add_nested_field",
        "Add nested field",
        "Schema",
        "METADATA",
        ["spark"],
        "ALTER TABLE {table} ADD COLUMN {path} {type}",
        description="Add a nested field to a struct.",
        params=[
            param("path", required=True, placeholder="payload.device"),
            param("type", required=True),
        ],
    ),
    op(
        "add_column_comment",
        "Add column with comment",
        "Schema",
        "METADATA",
        ["spark", "trino"],
        "ALTER TABLE {table} ADD COLUMN {column} {type} COMMENT '{comment}'",
        description="Add a column and column comment together.",
        params=[
            param("column", required=True),
            param("type", required=True, placeholder="string"),
            param("comment", placeholder="business description"),
        ],
    ),
    op(
        "drop_column",
        "Drop column",
        "Schema",
        "DESTRUCTIVE",
        E_SQL,
        "ALTER TABLE {table} DROP COLUMN {column}",
        description="Drop a column after downstream impact review.",
        params=[param("column", "column", required=True, placeholder="legacy_field")],
        gates=["consumer_impact_check", "approval_required", "restore_point_required"],
    ),
    op(
        "rename_column",
        "Rename column",
        "Schema",
        "DESTRUCTIVE",
        E_SQL,
        "ALTER TABLE {table} RENAME COLUMN {column} TO {new_name}",
        description="Rename a column after name-based reader checks.",
        params=[param("column", "column", required=True), param("new_name", required=True)],
        gates=["consumer_impact_check", "approval_required", "restore_point_required"],
    ),
    op(
        "promote_type",
        "Promote column type",
        "Schema",
        "METADATA",
        E_SQL,
        "ALTER TABLE {table} ALTER COLUMN {column} TYPE {type}",
        description="Promote a column type where the evolution is compatible.",
        params=[
            param("column", "column", required=True),
            param("type", required=True, placeholder="bigint"),
        ],
        gates=["schema_compatibility"],
    ),
    op(
        "update_column_comment",
        "Update column comment",
        "Schema",
        "METADATA",
        ["spark", "trino"],
        "ALTER TABLE {table} ALTER COLUMN {column} COMMENT '{comment}'",
        description="Set or update a column comment.",
        params=[param("column", "column", required=True), param("comment", required=True)],
    ),
    op(
        "drop_not_null",
        "Drop NOT NULL",
        "Schema",
        "METADATA",
        ["spark"],
        "ALTER TABLE {table} ALTER COLUMN {column} DROP NOT NULL",
        description="Relax a required column to nullable.",
        params=[param("column", "column", required=True)],
    ),
    op(
        "set_not_null",
        "Set NOT NULL",
        "Schema",
        "METADATA",
        ["spark"],
        "ALTER TABLE {table} ALTER COLUMN {column} SET NOT NULL",
        description="Require a column after validating existing rows.",
        params=[param("column", "column", required=True)],
        gates=["nullability_validation"],
    ),
    op(
        "reorder_column_first",
        "Move column first",
        "Schema",
        "METADATA",
        ["spark"],
        "ALTER TABLE {table} ALTER COLUMN {column} FIRST",
        description="Move a column to the beginning of the schema.",
        params=[param("column", "column", required=True)],
    ),
    op(
        "reorder_column_after",
        "Move column after",
        "Schema",
        "METADATA",
        ["spark"],
        "ALTER TABLE {table} ALTER COLUMN {column} AFTER {after_column}",
        description="Move a column after another column.",
        params=[param("column", "column", required=True), param("after_column", required=True)],
    ),
    op(
        "set_default",
        "Set column default",
        "Schema",
        "METADATA",
        E_SPARK,
        "ALTER TABLE {table} ALTER COLUMN {column} SET DEFAULT {value}",
        description="Set a format v3 default for new rows.",
        params=[
            param("column", "column", required=True),
            param("value", required=True, placeholder="0"),
        ],
        gates=["reader_compatibility_check"],
    ),
    op(
        "drop_nested_field",
        "Drop nested field",
        "Schema",
        "DESTRUCTIVE",
        ["spark"],
        "ALTER TABLE {table} DROP COLUMN {path}",
        description="Drop a nested field after consumer-impact checks.",
        params=[param("path", required=True, placeholder="payload.legacy")],
        gates=["consumer_impact_check", "approval_required", "restore_point_required"],
    ),
    op(
        "add_identity_partition",
        "Add identity partition",
        "Partition",
        "METADATA",
        ["spark", "trino"],
        "ALTER TABLE {table} ADD PARTITION FIELD {column}",
        description="Add an identity partition field.",
        params=[param("column", required=True, placeholder="dept")],
    ),
    op(
        "add_bucket_partition",
        "Add bucket partition",
        "Partition",
        "METADATA",
        ["spark", "trino"],
        "ALTER TABLE {table} ADD PARTITION FIELD bucket({bucket_count}, {column})",
        description="Add a bucket partition transform.",
        params=[
            param("bucket_count", "integer", default=16),
            param("column", required=True, placeholder="id"),
        ],
    ),
    op(
        "add_truncate_partition",
        "Add truncate partition",
        "Partition",
        "METADATA",
        ["spark", "trino"],
        "ALTER TABLE {table} ADD PARTITION FIELD truncate({width}, {column})",
        description="Add a truncate partition transform.",
        params=[
            param("width", "integer", default=4),
            param("column", required=True, placeholder="code"),
        ],
    ),
    op(
        "add_time_partition",
        "Add time partition",
        "Partition",
        "METADATA",
        ["spark", "trino"],
        "ALTER TABLE {table} ADD PARTITION FIELD {transform}({column})",
        description="Add a year, month, day, or hour time partition.",
        params=[
            param("transform", default="days", options=["years", "months", "days", "hours"]),
            param("column", default="occurred_at"),
        ],
    ),
    op(
        "add_named_partition",
        "Add named partition",
        "Partition",
        "METADATA",
        ["spark"],
        "ALTER TABLE {table} ADD PARTITION FIELD {transform} AS {name}",
        description="Add a partition field with an explicit name.",
        params=[
            param("transform", required=True, placeholder="bucket(8, id)"),
            param("name", required=True, placeholder="shard"),
        ],
    ),
    op(
        "drop_partition_field",
        "Drop partition field",
        "Partition",
        "METADATA",
        ["spark", "trino"],
        "ALTER TABLE {table} DROP PARTITION FIELD {field}",
        description="Remove a partition field for future writes.",
        params=[param("field", required=True, placeholder="days(occurred_at)")],
    ),
    op(
        "replace_partition_field",
        "Replace partition field",
        "Partition",
        "METADATA",
        ["spark"],
        "ALTER TABLE {table} REPLACE PARTITION FIELD {old_field} WITH {new_field}",
        description="Replace partition granularity or transform.",
        params=[
            param("old_field", required=True, placeholder="days(occurred_at)"),
            param("new_field", required=True, placeholder="hours(occurred_at)"),
        ],
    ),
    op(
        "write_ordered_by",
        "Write ordered by",
        "Partition",
        "METADATA",
        ["spark"],
        "ALTER TABLE {table} WRITE ORDERED BY {columns}",
        description="Set global write ordering.",
        params=[param("columns", required=True, placeholder="user_id, occurred_at")],
    ),
    op(
        "write_locally_ordered_by",
        "Write locally ordered by",
        "Partition",
        "METADATA",
        ["spark"],
        "ALTER TABLE {table} WRITE LOCALLY ORDERED BY {columns}",
        description="Set local file write ordering.",
        params=[param("columns", required=True, placeholder="user_id")],
    ),
    op(
        "write_distributed_by_partition",
        "Write distributed by partition",
        "Partition",
        "METADATA",
        ["spark"],
        "ALTER TABLE {table} WRITE DISTRIBUTED BY PARTITION",
        description="Distribute writes by partition.",
    ),
    op(
        "write_unordered",
        "Write unordered",
        "Partition",
        "METADATA",
        ["spark"],
        "ALTER TABLE {table} WRITE UNORDERED",
        description="Clear write ordering.",
    ),
    op(
        "set_identifier_fields",
        "Set identifier fields",
        "Partition",
        "METADATA",
        ["spark"],
        "ALTER TABLE {table} SET IDENTIFIER FIELDS {columns}",
        description="Set row identity fields for equality deletes, upserts, and CDC.",
        params=[param("columns", required=True, placeholder="id, region")],
    ),
    op(
        "drop_identifier_fields",
        "Drop identifier fields",
        "Partition",
        "METADATA",
        ["spark"],
        "ALTER TABLE {table} DROP IDENTIFIER FIELDS {columns}",
        description="Drop one or more row identity fields.",
        params=[param("columns", required=True, placeholder="region")],
    ),
    op(
        "insert_into",
        "Insert into",
        "DML",
        "WRITE",
        E_SQL,
        "INSERT INTO {table}\n{select_sql}",
        description="Append query results to a table.",
        params=[param("select_sql", required=True, placeholder="SELECT * FROM source.events")],
    ),
    op(
        "insert_values",
        "Insert values",
        "DML",
        "WRITE",
        ["spark", "trino", "embedded"],
        "INSERT INTO {table} VALUES ({values})",
        description="Insert literal values for small manual fixes.",
        params=[param("values", required=True, placeholder="1, 'page_view', current_timestamp()")],
    ),
    op(
        "insert_overwrite_static",
        "Insert overwrite static partition",
        "DML",
        "WRITE",
        ["spark", "trino"],
        "INSERT OVERWRITE {table} PARTITION ({partition})\n{select_sql}",
        description="Overwrite a static partition.",
        params=[
            param("partition", required=True, placeholder="dt='2026-06-01'"),
            param("select_sql", required=True, placeholder="SELECT * FROM staging.events"),
        ],
        approval_required=True,
    ),
    op(
        "insert_overwrite_dynamic",
        "Insert overwrite dynamic",
        "DML",
        "WRITE",
        ["spark"],
        "INSERT OVERWRITE {table}\n{select_sql}",
        description="Overwrite partitions dynamically based on query output.",
        params=[param("select_sql", required=True, placeholder="SELECT * FROM staging.events")],
        approval_required=True,
    ),
    op(
        "merge_matched_update",
        "Merge matched update",
        "DML",
        "WRITE",
        ["spark", "trino", "embedded"],
        (
            "MERGE INTO {table} t USING {source} s ON {join_condition} "
            "WHEN MATCHED THEN UPDATE SET {assignments}"
        ),
        description="Update matching rows through a merge.",
        params=[
            param("source", required=True, placeholder="staging.events_delta"),
            param("join_condition", required=True, placeholder="t.id = s.id"),
            param("assignments", required=True, placeholder="event_type = s.event_type"),
        ],
    ),
    op(
        "merge_not_matched_insert",
        "Merge not matched insert",
        "DML",
        "WRITE",
        ["spark", "trino", "embedded"],
        (
            "MERGE INTO {table} t USING {source} s ON {join_condition} "
            "WHEN NOT MATCHED THEN INSERT *"
        ),
        description="Insert new rows from a merge source.",
        params=[
            param("source", required=True, placeholder="staging.events_delta"),
            param("join_condition", required=True, placeholder="t.id = s.id"),
        ],
    ),
    op(
        "merge_upsert",
        "Merge upsert",
        "DML",
        "WRITE",
        ["spark", "trino", "embedded"],
        (
            "MERGE INTO {table} t USING {source} s ON {join_condition} "
            "WHEN MATCHED THEN UPDATE SET * WHEN NOT MATCHED THEN INSERT *"
        ),
        description="Apply an update-or-insert merge.",
        params=[
            param("source", required=True, placeholder="staging.events_delta"),
            param("join_condition", required=True, placeholder="t.id = s.id"),
        ],
    ),
    op(
        "update_rows",
        "Update rows",
        "DML",
        "WRITE",
        ["spark", "trino", "embedded"],
        "UPDATE {table} SET {assignments} WHERE {where}",
        description="Update rows matching a predicate.",
        params=[
            param("assignments", required=True, placeholder="event_type = 'redacted'"),
            param("where", "predicate", required=True, placeholder="event_id = 4820193"),
        ],
    ),
    op(
        "delete_rows",
        "Delete rows",
        "DML",
        "WRITE",
        E_SQL,
        "DELETE FROM {table} WHERE {where}",
        description="Delete rows matching a scoped predicate.",
        params=[param("where", "predicate", required=True, placeholder="user_id = 771")],
    ),
    op(
        "truncate_table",
        "Truncate table",
        "DML",
        "DESTRUCTIVE",
        ["spark", "trino"],
        "TRUNCATE TABLE {table}",
        description="Delete all rows by committing a new snapshot.",
        gates=[
            "dry_run_required",
            "restore_point_required",
            "protected_ref_check",
            "approval_required",
        ],
    ),
    op(
        "select_limit",
        "Sample rows",
        "Time travel",
        "READ",
        ["spark", "trino", "embedded"],
        "SELECT * FROM {table} LIMIT {limit}",
        description="Preview rows through the selected engine.",
        params=[param("limit", "integer", default=100)],
    ),
    op(
        "timestamp_as_of",
        "Read as of timestamp",
        "Time travel",
        "READ",
        ["spark", "trino", "embedded"],
        "SELECT * FROM {table} TIMESTAMP AS OF '{timestamp}'",
        description="Read table rows at a timestamp.",
        params=[param("timestamp", "timestamp", required=True, placeholder="2026-06-01 00:00:00")],
    ),
    op(
        "version_as_of_snapshot",
        "Read as of snapshot",
        "Time travel",
        "READ",
        ["spark", "trino"],
        "SELECT * FROM {table} VERSION AS OF {snapshot_id}",
        description="Read rows from a specific snapshot.",
        params=[param("snapshot_id", required=True, placeholder="8364920157712043")],
    ),
    op(
        "version_as_of_branch",
        "Read as of branch",
        "Time travel",
        "READ",
        ["spark"],
        "SELECT * FROM {table} VERSION AS OF '{branch}'",
        description="Read rows from a branch.",
        params=[param("branch", default="audit-2026-06")],
    ),
    op(
        "version_as_of_tag",
        "Read as of tag",
        "Time travel",
        "READ",
        ["spark"],
        "SELECT * FROM {table} VERSION AS OF '{tag}'",
        description="Read rows from a tag.",
        params=[param("tag", default="release-2026.06.09")],
    ),
    op(
        "incremental_read",
        "Incremental read",
        "Time travel",
        "READ",
        ["spark"],
        (
            "SELECT * FROM {table} "
            "/* start-snapshot-id={start_snapshot}, end-snapshot-id={end_snapshot} */"
        ),
        description="Read changes between snapshots.",
        params=[
            param("start_snapshot", required=True, placeholder="7588120049923847"),
            param("end_snapshot", required=True, placeholder="8364920157712043"),
        ],
    ),
    op(
        "branch_read",
        "Branch read",
        "Time travel",
        "READ",
        ["spark"],
        "SELECT * FROM {ns}.{table_name}.branch_{branch} LIMIT {limit}",
        description="Read from a branch-qualified table.",
        params=[param("branch", default="audit"), param("limit", "integer", default=100)],
    ),
    op(
        "tag_read",
        "Tag read",
        "Time travel",
        "READ",
        ["spark"],
        "SELECT * FROM {ns}.{table_name}.tag_{tag} LIMIT {limit}",
        description="Read from a tag-qualified table.",
        params=[param("tag", default="release"), param("limit", "integer", default=100)],
    ),
    op(
        "row_lineage_read",
        "Row lineage read",
        "Time travel",
        "READ",
        E_SPARK,
        "SELECT _row_id, _last_updated_sequence_number, * FROM {table} LIMIT {limit}",
        description="Preview format v3 row lineage columns.",
        params=[param("limit", "integer", default=100)],
    ),
    op(
        "meta_history",
        "Inspect history",
        "Metadata tables",
        "READ",
        ["spark", "trino"],
        "SELECT * FROM {table}.history",
        description="Query the table history metadata table.",
    ),
    op(
        "meta_snapshots",
        "Inspect snapshots",
        "Metadata tables",
        "READ",
        ["spark", "trino"],
        "SELECT * FROM {table}.snapshots",
        description="Query snapshot metadata.",
    ),
    op(
        "meta_files",
        "Inspect files",
        "Metadata tables",
        "READ",
        ["spark", "trino"],
        "SELECT * FROM {table}.files",
        description="Query live data-file metadata.",
    ),
    op(
        "meta_manifests",
        "Inspect manifests",
        "Metadata tables",
        "READ",
        ["spark", "trino"],
        "SELECT * FROM {table}.manifests",
        description="Query manifest file metadata.",
    ),
    op(
        "meta_partitions",
        "Inspect partitions",
        "Metadata tables",
        "READ",
        ["spark", "trino"],
        "SELECT * FROM {table}.partitions",
        description="Query partition summary metadata.",
    ),
    op(
        "meta_delete_files",
        "Inspect delete files",
        "Metadata tables",
        "READ",
        ["spark", "trino"],
        "SELECT * FROM {table}.delete_files",
        description="Query delete-file metadata.",
    ),
    op(
        "meta_entries",
        "Inspect entries",
        "Metadata tables",
        "READ",
        ["spark"],
        "SELECT * FROM {table}.entries",
        description="Query manifest entries.",
    ),
    op(
        "meta_refs",
        "Inspect refs",
        "Metadata tables",
        "READ",
        ["spark"],
        "SELECT * FROM {table}.refs",
        description="Query branch and tag refs.",
    ),
    op(
        "meta_all_data_files",
        "Inspect all data files",
        "Metadata tables",
        "READ",
        ["spark"],
        "SELECT * FROM {table}.all_data_files",
        description="Query data files across all snapshots.",
    ),
    op(
        "meta_all_delete_files",
        "Inspect all delete files",
        "Metadata tables",
        "READ",
        ["spark"],
        "SELECT * FROM {table}.all_delete_files",
        description="Query delete files across all snapshots.",
    ),
    op(
        "meta_all_manifests",
        "Inspect all manifests",
        "Metadata tables",
        "READ",
        ["spark"],
        "SELECT * FROM {table}.all_manifests",
        description="Query manifests across all snapshots.",
    ),
    op(
        "meta_position_deletes",
        "Inspect position deletes",
        "Metadata tables",
        "READ",
        ["spark"],
        "SELECT * FROM {table}.position_deletes",
        description="Query position delete rows.",
    ),
    op(
        "create_branch",
        "Create branch",
        "Branch and tag",
        "METADATA",
        E_SPARK,
        "ALTER TABLE {table} CREATE BRANCH {name}",
        description="Create a table branch at the current snapshot.",
        params=[param("name", default="audit-2026-06")],
    ),
    op(
        "create_branch_if_not_exists",
        "Create branch if not exists",
        "Branch and tag",
        "METADATA",
        E_SPARK,
        "ALTER TABLE {table} CREATE BRANCH IF NOT EXISTS {name}",
        description="Create a branch only when it is absent.",
        params=[param("name", default="audit-2026-06")],
    ),
    op(
        "create_branch_retention",
        "Create branch with retention",
        "Branch and tag",
        "METADATA",
        E_SPARK,
        "ALTER TABLE {table} CREATE BRANCH {name} RETAIN {days} DAYS",
        description="Create a branch with max ref age.",
        params=[param("name", default="audit-2026-06"), param("days", "integer", default=7)],
    ),
    op(
        "create_branch_snapshot_retention",
        "Create branch with snapshot retention",
        "Branch and tag",
        "METADATA",
        E_SPARK,
        "ALTER TABLE {table} CREATE BRANCH {name} WITH SNAPSHOT RETENTION {snapshots} SNAPSHOTS",
        description="Create a branch with snapshot-count retention.",
        params=[param("name", default="audit-2026-06"), param("snapshots", "integer", default=3)],
    ),
    op(
        "replace_branch",
        "Replace branch",
        "Branch and tag",
        "METADATA",
        E_SPARK,
        "ALTER TABLE {table} REPLACE BRANCH {name} AS OF VERSION {snapshot_id}",
        description="Move a branch to a snapshot.",
        params=[
            param("name", default="audit-2026-06"),
            param("snapshot_id", required=True, placeholder="7711203948855120"),
        ],
    ),
    op(
        "create_or_replace_branch",
        "Create or replace branch",
        "Branch and tag",
        "METADATA",
        E_SPARK,
        "ALTER TABLE {table} CREATE OR REPLACE BRANCH {name}",
        description="Create or reset a branch at the current snapshot.",
        params=[param("name", default="audit-2026-06")],
    ),
    op(
        "drop_branch",
        "Drop branch",
        "Branch and tag",
        "DESTRUCTIVE",
        E_SPARK,
        "ALTER TABLE {table} DROP BRANCH {name}",
        description="Drop a branch after protected-ref checks.",
        params=[param("name", required=True, placeholder="audit-2026-06")],
        gates=["protected_ref_check", "approval_required"],
    ),
    op(
        "create_tag",
        "Create tag",
        "Branch and tag",
        "METADATA",
        E_SPARK,
        "ALTER TABLE {table} CREATE TAG {name}",
        description="Create an immutable restore point tag.",
        params=[param("name", default="pre-change-restore")],
    ),
    op(
        "create_tag_retention",
        "Create tag with retention",
        "Branch and tag",
        "METADATA",
        E_SPARK,
        "ALTER TABLE {table} CREATE TAG {name} RETAIN {days} DAYS",
        description="Create a tag with an expiry policy.",
        params=[param("name", default="release-2026.06.09"), param("days", "integer", default=30)],
    ),
    op(
        "replace_tag",
        "Replace tag",
        "Branch and tag",
        "METADATA",
        E_SPARK,
        "ALTER TABLE {table} REPLACE TAG {name} AS OF VERSION {snapshot_id}",
        description="Move a tag to another snapshot.",
        params=[
            param("name", default="release-2026.06.09"),
            param("snapshot_id", required=True, placeholder="7401093847710022"),
        ],
    ),
    op(
        "drop_tag",
        "Drop tag",
        "Branch and tag",
        "DESTRUCTIVE",
        E_SPARK,
        "ALTER TABLE {table} DROP TAG {name}",
        description="Drop a tag after retention checks.",
        params=[param("name", required=True, placeholder="release-2026.06.09")],
        gates=["protected_ref_check", "approval_required"],
    ),
    op(
        "rollback_to_snapshot",
        "Roll back to snapshot",
        "Snapshots",
        "METADATA",
        E_SPARK,
        "CALL system.rollback_to_snapshot('{table}', {snapshot_id})",
        description="Move the current table pointer to a previous snapshot.",
        params=[param("snapshot_id", required=True, placeholder="7588120049923847")],
        approval_required=True,
        restore_point_required=True,
        gates=["snapshot_exists", "restore_point_required", "approval_required_in_prod"],
    ),
    op(
        "rollback_to_timestamp",
        "Roll back to timestamp",
        "Snapshots",
        "METADATA",
        E_SPARK,
        "CALL system.rollback_to_timestamp('{table}', TIMESTAMP '{timestamp}')",
        description="Roll back to the latest snapshot before a timestamp.",
        params=[param("timestamp", "timestamp", required=True, placeholder="2026-06-11 00:00:00")],
        approval_required=True,
        restore_point_required=True,
    ),
    op(
        "set_current_snapshot",
        "Set current snapshot",
        "Snapshots",
        "METADATA",
        E_SPARK,
        "CALL system.set_current_snapshot('{table}', {snapshot_id})",
        description="Set the current snapshot without ancestry constraints.",
        params=[param("snapshot_id", required=True, placeholder="7711203948855120")],
        approval_required=True,
        restore_point_required=True,
    ),
    op(
        "cherrypick_snapshot",
        "Cherry-pick snapshot",
        "Snapshots",
        "METADATA",
        E_SPARK,
        "CALL system.cherrypick_snapshot('{table}', {snapshot_id})",
        description="Apply a snapshot change on top of current state.",
        params=[param("snapshot_id", required=True, placeholder="7711203948855120")],
        approval_required=True,
        restore_point_required=True,
    ),
    op(
        "publish_changes",
        "Publish WAP changes",
        "Snapshots",
        "METADATA",
        E_SPARK,
        "CALL system.publish_changes('{table}', '{wap_id}')",
        description="Publish a staged write-audit-publish snapshot.",
        params=[param("wap_id", required=True, placeholder="wap-2026-06-14")],
    ),
    op(
        "fast_forward",
        "Fast-forward branch",
        "Snapshots",
        "METADATA",
        E_SPARK,
        "CALL system.fast_forward('{table}', '{target_branch}', '{source_branch}')",
        description="Fast-forward a target branch from a source branch.",
        params=[
            param("target_branch", default="main"),
            param("source_branch", default="audit-2026-06"),
        ],
    ),
    op(
        "rewrite_data_files",
        "Compact data files",
        "Maintenance",
        "REWRITE",
        E_MAINTENANCE,
        (
            "CALL system.rewrite_data_files(table => '{table}', strategy => '{strategy}', "
            "where => '{where}', "
            "options => map('target-file-size-bytes','{target_file_size_bytes}'))"
        ),
        description="Rewrite small files into target-sized data files.",
        params=[
            param("strategy", "enum", default="binpack", options=["binpack", "sort"]),
            param(
                "where", "predicate", default="true", placeholder="occurred_at >= DATE '2026-06-01'"
            ),
            param("sort_order", placeholder="zorder(user_id, occurred_at)", advanced=True),
            param("target_file_size_bytes", "integer", default=536870912, advanced=True),
            param("partial_progress", "boolean", default=False, advanced=True),
        ],
    ),
    op(
        "rewrite_manifests",
        "Rewrite manifests",
        "Maintenance",
        "REWRITE",
        E_MAINTENANCE,
        "CALL system.rewrite_manifests('{table}')",
        description="Consolidate manifest files for faster planning.",
    ),
    op(
        "rewrite_position_deletes",
        "Compact delete files",
        "Maintenance",
        "REWRITE",
        E_MAINTENANCE,
        (
            "CALL system.rewrite_position_delete_files("
            "table => '{table}', options => map('min-input-files','{min_input_files}'))"
        ),
        description="Rewrite position and equality delete files.",
        params=[param("min_input_files", "integer", default=2)],
    ),
    op(
        "expire_snapshots",
        "Expire snapshots",
        "Maintenance",
        "DESTRUCTIVE",
        E_MAINTENANCE,
        (
            "CALL system.expire_snapshots("
            "table => '{table}', older_than => TIMESTAMP '{older_than}', "
            "retain_last => {retain_last})"
        ),
        description="Remove old snapshot metadata while honoring retention gates.",
        params=[
            param("older_than", "timestamp", default="2026-06-01 00:00:00"),
            param("retain_last", "integer", default=5),
        ],
        gates=[
            "dry_run_required",
            "query_window_check",
            "protected_ref_check",
            "restore_point_required",
            "approval_required",
        ],
    ),
    op(
        "remove_orphan_files",
        "Remove orphan files",
        "Maintenance",
        "DESTRUCTIVE",
        E_MAINTENANCE,
        (
            "CALL system.remove_orphan_files("
            "table => '{table}', older_than => TIMESTAMP '{older_than}', "
            "dry_run => true, location => '{location}')"
        ),
        description="Delete unreferenced files after retention and path checks.",
        params=[
            param("older_than", "timestamp", default="2026-06-01 00:00:00"),
            param(
                "location",
                default="",
                placeholder="s3://dev-lakehouse/analytics/events",
                advanced=True,
            ),
            param("equal_authorities", default="", placeholder="host remap", advanced=True),
        ],
        gates=[
            "dry_run_required",
            "retention_window_min_3_days",
            "path_authority_check",
            "restore_point_required",
            "approval_required",
        ],
    ),
    op(
        "compute_table_stats",
        "Compute table stats",
        "Stats and CDC",
        "METADATA",
        E_SPARK,
        "CALL system.compute_table_stats(table => '{table}', columns => array({columns}))",
        description="Compute table-level statistics.",
        params=[param("columns", default="'event_id','user_id'")],
    ),
    op(
        "compute_partition_stats",
        "Compute partition stats",
        "Stats and CDC",
        "METADATA",
        E_SPARK,
        "CALL system.compute_partition_stats(table => '{table}')",
        description="Compute partition-level statistics.",
    ),
    op(
        "create_changelog_view",
        "Create changelog view",
        "Stats and CDC",
        "READ",
        E_SPARK,
        (
            "CALL system.create_changelog_view("
            "table => '{table}', options => map('start-snapshot-id','{start_snapshot}'))"
        ),
        description="Create a changelog view from snapshot metadata.",
        params=[param("start_snapshot", required=True, placeholder="7588120049923847")],
    ),
    op(
        "ancestors_of",
        "Snapshot ancestry",
        "Stats and CDC",
        "READ",
        E_SPARK,
        "CALL system.ancestors_of('{table}', {snapshot_id})",
        description="List snapshot ancestors.",
        params=[param("snapshot_id", required=True, placeholder="8364920157712043")],
    ),
    op(
        "snapshot_proc",
        "Snapshot external table",
        "Migration",
        "MIGRATION_ADMIN",
        E_SPARK,
        "CALL system.snapshot('{source_table}', '{table}')",
        description="Create an Iceberg snapshot copy of an external table.",
        params=[param("source_table", required=True, placeholder="hive_db.legacy_events")],
    ),
    op(
        "migrate_proc",
        "Migrate Hive or Spark table",
        "Migration",
        "MIGRATION_ADMIN",
        E_SPARK,
        "CALL system.migrate('{source_table}')",
        description="Migrate an existing table in-place.",
        params=[param("source_table", required=True, placeholder="hive_db.legacy_events")],
        approval_required=True,
    ),
    op(
        "add_files",
        "Add files",
        "Migration",
        "MIGRATION_ADMIN",
        E_SPARK,
        "CALL system.add_files(table => '{table}', source_table => '{source_table}')",
        description="Import data files into a table snapshot.",
        params=[param("source_table", required=True, placeholder="parquet.`s3://bucket/path`")],
    ),
    op(
        "register_table",
        "Register table",
        "Migration",
        "MIGRATION_ADMIN",
        ["spark", "embedded"],
        "CALL system.register_table('{table}', '{metadata_file}')",
        description="Register an existing Iceberg metadata file as a table.",
        params=[
            param(
                "metadata_file",
                required=True,
                placeholder="s3://bucket/table/metadata/v3.metadata.json",
            )
        ],
        gates=["same_location_collision_check", "metadata_file_exists"],
    ),
    op(
        "rewrite_table_path",
        "Rewrite table path",
        "Migration",
        "MIGRATION_ADMIN",
        E_SPARK,
        (
            "CALL system.rewrite_table_path("
            "table => '{table}', source_prefix => '{source_prefix}', "
            "target_prefix => '{target_prefix}')"
        ),
        description="Rewrite table metadata paths for replication or relocation.",
        params=[
            param("source_prefix", required=True, placeholder="s3://old-bucket/events"),
            param("target_prefix", required=True, placeholder="s3://new-bucket/events"),
        ],
        gates=["same_location_collision_check", "path_authority_check", "approval_required"],
    ),
    op(
        "create_view",
        "Create view",
        "Views",
        "METADATA",
        ["spark", "trino"],
        "CREATE VIEW {catalog}.{ns}.{view_name} AS\n{select_sql}",
        description="Create an Iceberg view.",
        params=[
            param("view_name", required=True, placeholder="daily_events"),
            param("select_sql", required=True, placeholder="SELECT * FROM analytics.events"),
        ],
    ),
    op(
        "create_or_replace_view",
        "Create or replace view",
        "Views",
        "METADATA",
        ["spark", "trino"],
        "CREATE OR REPLACE VIEW {catalog}.{ns}.{view_name} AS\n{select_sql}",
        description="Create or replace a view definition.",
        params=[
            param("view_name", required=True, placeholder="daily_events"),
            param("select_sql", required=True, placeholder="SELECT * FROM analytics.events"),
        ],
    ),
    op(
        "alter_view_as",
        "Alter view query",
        "Views",
        "METADATA",
        ["spark"],
        "ALTER VIEW {catalog}.{ns}.{view_name} AS\n{select_sql}",
        description="Replace a view query.",
        params=[
            param("view_name", required=True, placeholder="daily_events"),
            param("select_sql", required=True, placeholder="SELECT * FROM analytics.events"),
        ],
    ),
    op(
        "set_view_properties",
        "Set view properties",
        "Views",
        "METADATA",
        ["spark"],
        "ALTER VIEW {catalog}.{ns}.{view_name} SET TBLPROPERTIES ('{key}' = '{value}')",
        description="Set view properties.",
        params=[
            param("view_name", required=True, placeholder="daily_events"),
            param("key", required=True, placeholder="owner"),
            param("value", required=True, placeholder="data-platform"),
        ],
    ),
    op(
        "drop_view",
        "Drop view",
        "Views",
        "DESTRUCTIVE",
        ["spark", "trino"],
        "DROP VIEW {catalog}.{ns}.{view_name}",
        description="Drop a view after dependency checks.",
        params=[param("view_name", required=True, placeholder="daily_events")],
        gates=["dependency_check", "approval_required"],
    ),
    op(
        "show_views",
        "Show views",
        "Views",
        "READ",
        ["spark", "trino"],
        "SHOW VIEWS IN {catalog}.{ns}",
        description="List views in the current namespace.",
    ),
    op(
        "trino_optimize",
        "Trino optimize",
        "Engine specific",
        "REWRITE",
        E_TRINO,
        "ALTER TABLE {table} EXECUTE optimize(file_size_threshold => '{file_size_threshold}')",
        description="Compact files with Trino optimize.",
        params=[param("file_size_threshold", default="256MB")],
    ),
    op(
        "trino_optimize_manifests",
        "Trino optimize manifests",
        "Engine specific",
        "REWRITE",
        E_TRINO,
        "ALTER TABLE {table} EXECUTE optimize_manifests",
        description="Optimize manifests through Trino.",
    ),
    op(
        "trino_expire_snapshots",
        "Trino expire snapshots",
        "Engine specific",
        "DESTRUCTIVE",
        E_TRINO,
        (
            "ALTER TABLE {table} EXECUTE "
            "expire_snapshots(retention_threshold => '{retention_threshold}')"
        ),
        description="Expire snapshots through Trino.",
        params=[param("retention_threshold", default="7d")],
    ),
    op(
        "trino_remove_orphan_files",
        "Trino remove orphan files",
        "Engine specific",
        "DESTRUCTIVE",
        E_TRINO,
        (
            "ALTER TABLE {table} EXECUTE "
            "remove_orphan_files(retention_threshold => '{retention_threshold}')"
        ),
        description="Remove orphan files through Trino.",
        params=[param("retention_threshold", default="7d")],
        gates=[
            "dry_run_required",
            "retention_window_min_3_days",
            "path_authority_check",
            "restore_point_required",
            "approval_required",
        ],
    ),
    op(
        "trino_drop_extended_stats",
        "Trino drop extended stats",
        "Engine specific",
        "METADATA",
        E_TRINO,
        "ALTER TABLE {table} EXECUTE drop_extended_stats",
        description="Drop Trino extended statistics.",
    ),
    op(
        "trino_metadata_table",
        "Trino metadata table",
        "Engine specific",
        "READ",
        E_TRINO,
        'SELECT * FROM "{ns}"."{table_name}${metadata_table}"',
        description="Read a Trino Iceberg metadata table.",
        params=[param("metadata_table", default="snapshots")],
    ),
    op(
        "duckdb_dml",
        "Embedded DML",
        "Engine specific",
        "WRITE",
        E_DUCKDB,
        "{statement}",
        description="Run an embedded engine DML statement against an attached Iceberg table.",
        params=[
            param("statement", required=True, placeholder="UPDATE iceberg_table SET ... WHERE ...")
        ],
    ),
    op(
        "refresh_managed_table",
        "Refresh managed Iceberg table",
        "Engine specific",
        "REWRITE",
        ["snowflake"],
        "ALTER ICEBERG TABLE {table} REFRESH",
        description="Refresh a managed Iceberg table in an external engine.",
    ),
    op(
        "set_parquet_settings",
        "Set Parquet write settings",
        "Tuning",
        "METADATA",
        E_SQL,
        (
            "ALTER TABLE {table} SET TBLPROPERTIES ("
            "'write.parquet.compression-codec' = '{codec}', "
            "'write.parquet.compression-level' = '{compression_level}', "
            "'write.parquet.row-group-size-bytes' = '{row_group_size_bytes}')"
        ),
        description="Tune Parquet codec, level, and row-group size for future writes.",
        params=[
            param(
                "codec",
                "enum",
                default="zstd",
                options=["zstd", "snappy", "gzip", "lz4", "uncompressed"],
            ),
            param("compression_level", "integer", default=3),
            param("row_group_size_bytes", "integer", default=134_217_728, advanced=True),
        ],
    ),
    op(
        "rewrite_parquet_encoding",
        "Re-encode Parquet files",
        "Tuning",
        "REWRITE",
        E_MAINTENANCE,
        (
            "CALL system.rewrite_data_files(table => '{table}', "
            "options => map('target-file-size-bytes','{target_file_size_bytes}'))"
        ),
        description="Rewrite existing data files with the current Parquet settings.",
        params=[param("target_file_size_bytes", "integer", default=536_870_912)],
    ),
    op(
        "set_write_distribution",
        "Set write distribution mode",
        "Tuning",
        "METADATA",
        E_SQL,
        "ALTER TABLE {table} SET TBLPROPERTIES ('write.distribution-mode' = '{mode}')",
        description="Control pre-write shuffle to reduce small-file creation at the source.",
        params=[param("mode", "enum", default="hash", options=["none", "hash", "range"])],
    ),
    op(
        "cleanup_old_data",
        "Clean up old data",
        "Retention",
        "DESTRUCTIVE",
        E_MAINTENANCE,
        "DELETE FROM {table} WHERE {time_column} < TIMESTAMP '{cutoff}'",
        description="Enforce a data-retention TTL by deleting rows older than a cutoff.",
        params=[
            param("time_column", default="occurred_at", placeholder="occurred_at"),
            param("cutoff", "timestamp", required=True, placeholder="2026-03-19 00:00:00"),
            param("mode", "enum", default="soft", options=["soft", "hard", "archive"]),
            param("archive_location", placeholder="s3://cold/events/", advanced=True),
        ],
        gates=[
            "dry_run_required",
            "max_delete_pct_guard",
            "restore_point_required",
            "approval_required",
        ],
    ),
    op(
        "backfill_default",
        "Backfill column default",
        "Retention",
        "WRITE",
        E_MAINTENANCE,
        "UPDATE {table} SET {column} = {default_value} WHERE {column} IS NULL",
        description="Physically populate existing NULLs with a v3 column default.",
        params=[
            param("column", "column", required=True, placeholder="device_type"),
            param("default_value", required=True, placeholder="'unknown'"),
            param(
                "predicate",
                "predicate",
                placeholder="occurred_at >= DATE '2026-01-01'",
                advanced=True,
            ),
        ],
        gates=["dry_run_required", "affected_row_estimate", "restore_point_required"],
        restore_point_required=True,
    ),
    op(
        "create_summary_table",
        "Create summary table",
        "Tuning",
        "WRITE",
        E_SQL,
        "CREATE TABLE {catalog}.{namespace}.{summary_name} USING iceberg AS\n{definition}",
        description="Self-managed materialized-view fallback: a precomputed aggregate table.",
        params=[
            param("namespace", default="{ns}"),
            param("summary_name", required=True, placeholder="events_daily_region"),
            param(
                "definition",
                required=True,
                placeholder="SELECT day, region, count(*) FROM events GROUP BY 1, 2",
            ),
        ],
    ),
    op(
        "refresh_summary_table",
        "Refresh summary table",
        "Tuning",
        "REWRITE",
        ["spark", "trino", "embedded"],
        "INSERT OVERWRITE {table}\n{definition}",
        description="Recompute a self-managed summary/aggregate table.",
        params=[param("definition", required=True, placeholder="SELECT ... GROUP BY ...")],
    ),
]

OPERATIONS = [OperationDescriptor.model_validate(item) for item in RAW_OPERATIONS]
OPERATION_BY_ID = {operation.id: operation for operation in OPERATIONS}
